name: Java Maven Cucumber CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      CUCUMBER_TAGS:
        description: 'Cucumber tags for test execution'
        required: false
        default: '@veterinarian'  # Default tag

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build and run tests
        run: mvn clean install "-Dcucumber.filter.tags=@veterinarian"
        # Uncomment if you want to use dynamic tags
        # run: mvn clean install "-Dcucumber.filter.tags=${{ github.event.inputs.CUCUMBER_TAGS }}"

      - name: Generate Cucumber HTML Report
        if: always()
        run: |
          # Convert Cucumber JSON report to HTML
          mvn net.masterthought:maven-cucumber-reporting:5.5.3:generate \
            -DcucumberOutput=target/cucumber/cucumber.json\
            -DoutputDirectory=target/Report/cucumber-reports/html

      - name: Archive Cucumber Reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-reports
          path: '**/target/cucumber-reports/html/**'

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Build successful! Cucumber Report: ${{ github.run_url }}/artifacts/cucumber-html-reports\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Build failed! GitHub Actions Build: ${{ github.run_url }}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
